Kotlin. Homework #2. Task #2
alexdtat/SPbU-Kotlin-course pull request #2
Opened 2022-03-13 12:35 UTC by alexdtat

Task 2 solution and SieveOfEratosthenes library have been added.

2022-03-18 12:43 UTC, alexdtat commented
Огромное число коммитов, потому что у меня в какой-то момент возникли проблемы с подгрузкой зависимостей (Егор Сергеевич посоветовал выбрать Kotlin 1.6.0) и не сразу разобрался с локальным detekt. :(

2022-03-18 13:49 UTC, GirZ0n requested changes
Я призываю тебя убрать класс и сделать всего одну функцию, которая будет возвращать список простых чисел, потому что сейчас прям оверкил какой-то)) К тому же здесь есть проблема, связанная с мутабельностью переменной `primes`. Вот проблемный код:
```kotlin
val sieve = SieveOfEratosthenes(1)
var primes = sieve.getPrimes()

primes.add(42)
println(primes.joinToString(", "))  
// Как и ожидается выведет '42'

primes = sieve.getPrimes()
println(primes.joinToString(", ")) 
// Выведет не пустую строку, а '42', 
// что неожиданно, так как от решета с границей равной 1 ожидаешь увидеть пустую строку.
```
Есть способы как это можно исправить, оставив класс, но даже там это будет не очень хорошо выглядеть, так что просто перепиши это в виде одной функции и всё будет норм)

2022-03-18 13:49 UTC, GirZ0n commented on src/main/kotlin/homework/homework2/task_2.kt
> +    var stringNumber: String? = ""
А зачем эта строчка вообще нужна?)) Почему нельзя просто в строчке с номером 11 написать так: `val stringNumber = readLine()`?

2022-03-18 13:49 UTC, GirZ0n commented on src/main/kotlin/homework/homework2/task_2.kt
> +            var number = 0
Ну вот тут кажется тоже можно без это инициализации обойтись:
```kotlin
try {
    ...
    if (stringNumber == null) {
        println("Null input. Please, try again:")
        return
    }
    
    val number = stringNumber.toInt()
    ....
}
```

2022-03-18 13:49 UTC, GirZ0n commented on src/main/kotlin/homework/homework2/task_2.kt
> +            val newSieveOfEratosthenes = SieveOfEratosthenes(number)
Я бы просто `sieve` назвал бы)

2022-03-18 13:49 UTC, GirZ0n commented on src/main/kotlin/homework/homework2/task_2.kt
> +            var number = 0
И вообще ты можешь просто сразу считать строку и попробовать её инвертировать в число: `val number = readLine()?.toIntOrNull()`. В этом случае ловить `NumberFormatException` не нужно будет.

2022-03-18 13:49 UTC, GirZ0n commented on src/main/kotlin/homework/homework2/task_2.kt
> +    var stringNumber: String? = ""
Тебе даже идейка подсказывает, что тут что-то не так)
![Screenshot from 2022-03-18 16-07-21](https://user-images.githubusercontent.com/55441714/159008389-39273051-13ac-4ce9-8899-d1405c8fa4d6.png)

2022-03-18 13:49 UTC, GirZ0n commented on src/main/kotlin/libraries/sieveOfEratosthenes/SieveOfEratosthenes.kt
> +    private var isPrime = Array(1) { _ -> true }
Ну раз тебе переменная явно не нужно, то и не используй её))
`private var isPrime = Array(1) { true }`

2022-03-18 13:49 UTC, GirZ0n commented on src/main/kotlin/libraries/sieveOfEratosthenes/SieveOfEratosthenes.kt
> +    }
Во-первых, у массивов есть метод [`joinToString`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/join-to-string.html#jointostring).
Во-вторых, мне кажется этот класс не должен заниматься печатью) С учётом того, что ты теперь узнал про `joinToString` печать можно произвести в одну строчку и сразу внутри `main`.

2022-03-18 13:49 UTC, GirZ0n commented on src/main/kotlin/libraries/sieveOfEratosthenes/SieveOfEratosthenes.kt
> +        isPrime = Array(upperBound + 1) { _ -> true }
Аналогичная проблема: если не нужна переменная, то не используй)
`isPrime = Array(upperBound + 1) { true }`

2022-03-18 13:49 UTC, GirZ0n commented on src/test/kotlin/libraries/sieveOfEratosthenes/SieveOfEratosthenesTest.kt
> +    }
А чего тут не стал сообщение проверять? (((

2022-03-18 13:49 UTC, GirZ0n commented on src/main/kotlin/libraries/sieveOfEratosthenes/SieveOfEratosthenes.kt
> +        val optimisedUpperBound = kotlin.math.floor(kotlin.math.sqrt(upperBound.toDouble())).toInt()
Уфф, давай мы просто импортируем эти функции и будем их вызывать как обычно, а не через FQ name)

2022-03-18 13:49 UTC, GirZ0n commented on src/main/kotlin/libraries/sieveOfEratosthenes/SieveOfEratosthenes.kt
> +                (2 * index..upperBound step index).forEach { isPrime[it] = false }
Давай тут ещё скобочки поставим, чтобы читалось чуть лучше: `((2 * index)..upperBound step index).forEach { isPrime[it] = false }`

2022-03-18 13:49 UTC, GirZ0n commented on src/main/kotlin/libraries/sieveOfEratosthenes/SieveOfEratosthenes.kt
> +        }
Здесь кажется может пригодится [`mapIndexedNotNull`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/map-indexed-not-null.html#mapindexednotnull).

2022-03-18 13:49 UTC, GirZ0n commented on src/main/kotlin/libraries/sieveOfEratosthenes/SieveOfEratosthenes.kt
> +    }
В Kotlin не надо писать getter'ы и setter'ы. Они автоматически добавляются на этапе компиляции. Поэтому достаточно сделать переменную `primes` публичной. Из-за того, что она объявлена как `val` её нельзя перезаписать, но при этом к ней есть доступ.

2022-03-18 13:57 UTC, GirZ0n commented
Кстати, а почему у тебя ПР называется `Kotlin. Homework #2. Task #2`? Это задание вроде к первому дз относится.

2022-03-18 14:06 UTC, alexdtat commented
> Кстати, а почему у тебя ПР называется `Kotlin. Homework #2. Task #2`? Это задание вроде к первому дз относится.

Первое, вроде, было с созданием репо и т.д., но раз оно не считается, то сейчас поправлю.

2022-03-18 21:57 UTC, alexdtat commented on src/main/kotlin/homework/homework2/task_2.kt
> +            var number = 0
> 

А как тогда без исключения обрабатывать всякие ситуации, когда пользователь вводит слово вместо числа?

И как лучше действовать в ситуации, когда я хочу иметь `val` вместо `var`, но поскольку оно объявляется где-нибудь в `if else`, его нельзя использовать в области видимости на уровень выше? Например:


```
if(condition(someArgument)) {
...
val result = someFunction(someArgument) // не могу определить раньше, потому что надо проверить условие
}
// хочу использовать неизменяемый result, но он на другом уровне видимости; if раздувать тоже не хочу
```

2022-03-18 22:38 UTC, alexdtat commented on src/main/kotlin/homework/homework2/task_2.kt
> +            var number = 0
> И вообще ты можешь просто сразу считать строку и попробовать её инвертировать в число: `val number = readLine()?.toIntOrNull()`. В этом случае ловить `NumberFormatException` не нужно будет.

Так я же тогда без исключения не смогу обрабатывать ввод неприводимых к инту строк.

И как, кстати, лучше действовать в такой ситуации: допустим, я хочу в зависимости от условия вызывать конструктор и инициализировать какой-нибудь объект, но при этом оставлять его неизменяемым (тот же `val`), а потом продолжать его использование вне блока `if else`. Например:
```
if(condition(argument)) {
val myObject = SomeObject(argument) // нельзя инициализировать раньше, но хочется val, а не var
...
} else {
val myObject = SomeObject(const) // нельзя инициализировать раньше, но хочется val, а не var
...
}
/* хочу использовать myObject не делая разницы между прошлыми ветвлениями, но он на другом уровне видимости; раздувать if else также не хочу*/
```

Мб тут есть какое-то очевидное решение, но я его не знаю/туплю. Хочется минимизировать всякие костыли вроде промежуточных переменных или `Boolean` флажков.

2022-03-19 08:45 UTC, GirZ0n commented on src/main/kotlin/homework/homework2/task_2.kt
> +            var number = 0
Кажется, что можно сделать как-то так:
```kotlin
val myObject = if (predicate(argument)) SomeObject(argument) else SomeObject(constant)
```

2022-03-19 14:02 UTC, alexdtat commented
Единственное, я не совсем уверен, что правильно понял идею, стоящую за `mapUndexedNotNull`.

2022-03-19 15:10 UTC, GirZ0n requested changes
Ну вот теперь вообще прям супер круто получилось) Исправь только конфликт) Ты это можешь сделать либо на гитхабе, либо в идейке, попросив её смёрджить `master` в `hw_2_task_2`.

2022-03-19 15:10 UTC, GirZ0n commented on src/main/kotlin/libraries/sieveOfEratosthenes/sieveOfEratosthenes.kt
> +            ((2 * index)..upperBound step index).forEach { isPrime[it] = false }
Да, ты можешь не ставить фигурные скобки в данном случае, но давай будем их ставить всегда, чтобы код был согласованным) Просто в общем случае скобки должны быть)

2022-03-19 15:10 UTC, GirZ0n commented on src/main/kotlin/libraries/sieveOfEratosthenes/sieveOfEratosthenes.kt
> +    return primes
Ага, ты верно понял идею)

Ещё немного замечаний:
1. Зачем записывать результат в переменную и сразу же её возвращать?) Верни сразу результат)
2. Здесь можно `if` записать в одну строчку: `isPrime.mapIndexedNotNull {index, _ -> if (isPrime[index]) index else null}`. Кажется, что так будет покрасивше)
3. Почему ты игнорируешь второй элемент?) Он же как раз будет равен `isPrime[index]`. Можно вот так написать: `isPrime.mapIndexedNotNull {index, value -> if (value) index else null}`.

2022-03-19 15:10 UTC, GirZ0n commented on src/main/kotlin/homework/homework1/task_2.kt
> +                val sieved = sieveOfEratosthenes(number)
Кажется, что лучше назвать переменную просто `primes`)

2022-03-19 15:10 UTC, GirZ0n commented on src/main/kotlin/libraries/sieveOfEratosthenes/sieveOfEratosthenes.kt
> +            ((2 * index)..upperBound step index).forEach { isPrime[it] = false }
В `main` у тебя тоже есть такая же проблема.

2022-03-19 15:38 UTC, alexdtat commented on src/main/kotlin/libraries/sieveOfEratosthenes/sieveOfEratosthenes.kt
> +            ((2 * index)..upperBound step index).forEach { isPrime[it] = false }
Да, я почитал немного про кодстайл, там вроде только про многострочные было написано и в примере не стояли, так что решил убрать. Но мне тоже больше с ними нравится. 🙂

2022-03-19 15:41 UTC, alexdtat commented on src/main/kotlin/libraries/sieveOfEratosthenes/sieveOfEratosthenes.kt
> +    return primes
> Ага, ты верно понял идею)
> 
> Ещё немного замечаний:
> 
> 1. Зачем записывать результат в переменную и сразу же её возвращать?) Верни сразу результат)
> 2. Здесь можно `if` записать в одну строчку: `isPrime.mapIndexedNotNull {index, _ -> if (isPrime[index]) index else null}`. Кажется, что так будет покрасивше)
> 3. Почему ты игнорируешь второй элемент?) Он же как раз будет равен `isPrime[index]`. Можно вот так написать: `isPrime.mapIndexedNotNull {index, value -> if (value) index else null}`.

А, вот оно что. Я ночью уже что-то не очень понял из документации, что там второй элемент означает, и сделал так. Действительно, теперь всё встало на свои места. 👀

2022-03-19 16:19 UTC, GirZ0n approved these changes
:fire:

2022-03-22 17:18 UTC, SpirinEgor approved these changes

2022-03-22 17:18 UTC, merged