Kotlin. Homework #2. Task #3
alexdtat/SPbU-Kotlin-course pull request #3
Opened 2022-03-13 13:04 UTC by alexdtat

Task 3 solution and PerformedCommandStorage library have been added.

2022-03-19 14:24 UTC, alexdtat commented
Много коммитов с упавшим билдом, потому что у меня в какой-то момент возникли проблемы с подгрузкой зависимостей (Егор Сергеевич посоветовал выбрать Kotlin 1.6.0) и не сразу разобрался с локальным detekt. :(

PR сначала отнёс ко второй домашке, потому что думал, что создание репо и т.д. считалось за первую. В другом PR меня поправили, так что здесь тоже поменял.

2022-03-24 20:29 UTC, illided requested changes

2022-03-24 20:29 UTC, illided commented on src/main/kotlin/homework/homework1/task_3.kt
> +        "abort" -> {}
Давай завернем команды в Enum

2022-03-24 20:29 UTC, illided commented on src/main/kotlin/homework/homework1/task_3.kt
> +            if (numberOfArguments < 1)
Вот эту всю логику вынести бы куда нибудь чтобы не раздувать when

2022-03-24 20:29 UTC, illided commented on src/main/kotlin/homework/homework1/task_3.kt
> +    println(
Здесь можно сделать красивое сообщение с помощью `"""`, а потом использовать `trimIndent`

2022-03-24 20:29 UTC, illided commented on src/main/kotlin/libraries/PerformedCommandStorage/PerformedCommandStorage.kt
> +    fun directCommand()
Что значит прямая команда?)

2022-03-24 20:29 UTC, illided commented on src/main/kotlin/homework/homework1/task_3.kt
> +            processCommand(inputSplitted, commandStorage)
Подожди, то есть ты в случае null input выполняешь предыдущую команду?

2022-03-24 20:29 UTC, illided commented on src/main/kotlin/homework/homework1/task_3.kt
> +                "You cannot undo a command in the empty storage." -> println("Command storage is empty.")
Не нравится мне это. Почему просто не вывести сообщение `exception`?

2022-03-24 20:29 UTC, illided commented on src/main/kotlin/libraries/PerformedCommandStorage/PerformedCommandStorage.kt
> +class AddToEnd(private val processedList: ArrayList<Int>, private val addedNumber: Int) : Command {
Почему именно `ArrayList` а не интерфейс `MutableList`?

2022-03-24 20:29 UTC, illided commented on src/main/kotlin/libraries/PerformedCommandStorage/PerformedCommandStorage.kt
> +class Swap(private val processedList: ArrayList<Int>, private val position1: Int, private val position2: Int) :
Не swap а поменять позицию одного элемента)

2022-03-24 20:29 UTC, illided commented on src/main/kotlin/libraries/PerformedCommandStorage/PerformedCommandStorage.kt
> +    fun addToEnd(addedNumber: Int) {
Давай лучше как раз сделаем просто execute публичной и пользователь сам будет создавать команды и добавлять в сторадж

2022-03-24 20:29 UTC, illided commented on src/main/kotlin/libraries/PerformedCommandStorage/PerformedCommandStorage.kt
> +    val processedList = ArrayList<Int>()
Здесь можно сделать два поля: одно приватное мы меняем а другое публичное выдает неизменяемый лист. Ну или можно как крутые ребята отнаследоваться от какого нибудь интерфейса)

2022-03-24 20:29 UTC, illided commented on src/main/kotlin/libraries/PerformedCommandStorage/PerformedCommandStorage.kt
> +        require(position1 in 0..upperBound && position2 in 0..upperBound) {
`in processedList.indices`

2022-03-27 14:25 UTC, alexdtat commented on src/main/kotlin/libraries/PerformedCommandStorage/PerformedCommandStorage.kt
> +    fun directCommand()
> Что значит прямая команда?)

Не обратная. 😁

2022-03-27 17:39 UTC, alexdtat commented on src/main/kotlin/libraries/PerformedCommandStorage/PerformedCommandStorage.kt
> +    val processedList = ArrayList<Int>()
> Здесь можно сделать два поля: одно приватное мы меняем а другое публичное выдает неизменяемый лист. Ну или можно как крутые ребята отнаследоваться от какого нибудь интерфейса)

А зачем здесь интерфейс? Чем плох вариант, например, с приватным изменяемым списком и геттером, возвращающим неизменяемый?

2022-03-28 09:04 UTC, illided commented on src/main/kotlin/libraries/PerformedCommandStorage/PerformedCommandStorage.kt
> +    val processedList = ArrayList<Int>()
Я говорил про какой-нибудь интерфейс List.

Просто кажется удобным в коде объявить:
`val revertableList = revertableListOf()`
А потом можешь его использовать как обычный список, при этом добавляя всякие действия и отменяя их

2022-04-21 21:18 UTC, alexdtat commented on src/main/kotlin/libraries/PerformedCommandStorage/PerformedCommandStorage.kt
> +    val processedList = ArrayList<Int>()
> Я говорил про какой-нибудь интерфейс List.
> 
> Просто кажется удобным в коде объявить: `val revertableList = revertableListOf()` А потом можешь его использовать как обычный список, при этом добавляя всякие действия и отменяя их

Получается, тогда пользователь не будет взаимодействовать с самим хранилищем и создавать команды, а вместо этого будет просто видеть отнаследованный от списка интерфейс, где есть .addToEnd, .addToBeginning, .move и .undo?

2022-04-22 18:10 UTC, alexdtat commented on src/main/kotlin/libraries/PerformedCommandStorage/PerformedCommandStorage.kt
> +    fun addToEnd(addedNumber: Int) {
> Давай лучше как раз сделаем просто execute публичной и пользователь сам будет создавать команды и добавлять в сторадж

Вообще, тогда там будут проблемы с доступом к processedList, потому что Mutable вариант поля приватный, а команды создаются где-то отдельно от хранилища пользователем.

2022-04-22 18:52 UTC, alexdtat commented
Аналогично, понимаю, что после дедлайна, но можно хотя бы не на оценку ревью? С наследованием от интерфейсов я не очень пока понял (думал отнаследоваться просто от `List`, но в реализации команд используются методы `MutableList`, а если наследоваться от него, то тогда не очень ясно, в чём будет смысл и какая должна быть архитектура программы. :(

Поэтому просто сделал два поля.

2022-04-24 14:49 UTC, illided requested changes

2022-04-24 14:49 UTC, illided commented on src/main/kotlin/libraries/PerformedCommandStorage/PerformedCommandStorage.kt
> +fun moveArgumentsCheck(origin: Int, destination: Int, processedList: MutableList<Int>) {
Почему это не закинуть в `init` класса `Move`?

2022-04-24 14:49 UTC, illided commented on src/main/kotlin/homework/homework1/task_3.kt
> +fun PerformedCommandStorage.addToEnd(addedNumber: Int) {
Вот за это хочу отдельно похвалить
Как мне кажется эталонное использование `extension` функций :)

2022-04-24 14:49 UTC, illided commented on src/main/kotlin/homework/homework1/task_3.kt
> +            '${PossibleCommands.ADD_TO_BEGINNING.stringCommand} x'
Можно в енам добавить еще одно поле help и там прописать вот эти подсказки
Здесь это просто собрать

2022-04-24 14:49 UTC, illided commented on src/main/kotlin/homework/homework1/task_3.kt
> +        var inputSplitted: List<String>
Зачем эту переменную обьявлять вне цикла?

2022-04-24 14:49 UTC, illided commented on src/main/kotlin/homework/homework1/task_3.kt
> +                "You cannot undo a command in the empty storage." -> println("Command storage is empty.")
Если хочется так сделать, то лучше создать свои exception а не делать when по строкам

2022-04-24 14:49 UTC, illided commented on src/main/kotlin/libraries/PerformedCommandStorage/PerformedCommandStorage.kt
> +            "Cannot swap in the empty storage."
Ставь по возможности всегда скобки, даже если строка одна

2022-04-24 14:49 UTC, illided commented on src/test/kotlin/libraries/PerformedCommandStorage/PerformedCommandStorageTest.kt
> +
А зачем этот пропуск?)

2022-04-24 14:49 UTC, illided commented on src/main/kotlin/homework/homework1/task_3.kt
> +fun numberOfArgumentsIsCorrect(numberOfArguments: Int, command: String): Boolean {
Информацию о количестве аргументов можно в тот же енам)

2022-04-24 14:49 UTC, illided commented on src/main/kotlin/homework/homework1/task_3.kt
> +    while (currentCommand != "abort") {
Давай сделаем проще. Сразу уйдем от строкового представления к енаму (например с помощью одного when) и дальше работать исключительно с енамом

2022-04-24 14:49 UTC, illided commented on src/main/kotlin/homework/homework1/task_3.kt
> +            println("\nThe processed Int list:\n" + commandStorage.processedList.joinToString(", "))
Много логики в одной строчке. Лучше разбить

2022-04-24 14:49 UTC, illided commented on src/main/kotlin/homework/homework1/task_3.kt
> +fun processCommand(inputSplitted: List<String>, commandStorage: PerformedCommandStorage) {
А здесь чего не сделал extension?

2022-04-24 14:49 UTC, illided commented on src/main/kotlin/homework/homework1/task_3.kt
> +            println(exceptionFormat.message + " Cannot convert into Int.")
Не можешь превратить в инт?
Кого? Что?)
Лучше что то подробнее сказать: пользователь ты написал чепуху вместо числа

2022-04-30 13:02 UTC, alexdtat commented on src/main/kotlin/libraries/PerformedCommandStorage/PerformedCommandStorage.kt
> +fun moveArgumentsCheck(origin: Int, destination: Int, processedList: MutableList<Int>) {
> Почему это не закинуть в `init` класса `Move`?

У меня по архитектуре получается, что до момента исполнения команда не знает о том, с каким списком работает, поэтому нельзя на этапе инициализации узнать размер списка. Я могу поменять, но, честно говоря, не знаю, какая архитектура здесь лучше? И если менять, то везде или только в `Move`?

2022-04-30 14:02 UTC, illided commented on src/main/kotlin/libraries/PerformedCommandStorage/PerformedCommandStorage.kt
> +fun moveArgumentsCheck(origin: Int, destination: Int, processedList: MutableList<Int>) {
А, да, действительно.
Тогда просто запихай этот метод в `Move`, чтобы все было на своем месте

2022-05-01 16:36 UTC, alexdtat commented
Обнаружил, что у меня некорректная команда `move i j` всё равно добавляется в хранилище. Добавил отдельную функцию проверки аргументов с возвращением исключения, потому что если кидать исключение где-то непосредственно внутри `Move.command()`, то получится, что внутри `execute` придётся либо повторно перебрасывать его (детект не оценит), либо обрабатывать (а хочется, чтобы обрабатывал пользователь). Других решений проблемы с добавлением некорректных команд не придумал. :(

2022-05-05 15:13 UTC, illided approved these changes
Теперь выглядит неплохо :)
Насчет исключений: я думаю можно просто его в command кинуть, тогда оно пролетит через execute и до твоего основного when и там уже обработать. Не совсем тут вижу проблемы

2022-05-05 15:13 UTC, illided commented on src/main/kotlin/libraries/PerformedCommandStorage/PerformedCommandStorage.kt
> +    override val message: String
Насколько я помню можно просто через равно прописать

2022-05-05 15:13 UTC, illided commented on src/main/kotlin/libraries/PerformedCommandStorage/PerformedCommandStorage.kt
> +    fun checkArgumentsException(processedList: MutableList<Int>): IllegalArgumentException?
Можно сделать имплементацию по умолчанию

2022-05-05 17:24 UTC, alexdtat commented
> Теперь выглядит неплохо :) Насчет исключений: я думаю можно просто его в command кинуть, тогда оно пролетит через execute и до твоего основного when и там уже обработать. Не совсем тут вижу проблемы

С исключением проблема в том, что, как я понимаю, тогда в случае некорректных аргументов в move сама команда исполнена не будет, но она добавится в хранилище, после чего при отмене либо выскочит ошибка, либо надо будет повторно проверять аргументы (но мне вообще идея добавления некорректной команды в хранилище кажется не очень хорошей), а при нынешнем решении такого не произойдёт.

2022-05-06 06:37 UTC, illided commented
> С исключением проблема в том, что, как я понимаю, тогда в случае некорректных аргументов в move сама команда исполнена не будет, но она добавится в хранилище, после чего при отмене либо выскочит ошибка, либо надо будет повторно проверять аргументы (но мне вообще идея добавления некорректной команды в хранилище кажется не очень хорошей), а при нынешнем решении такого не произойдёт.

Кстати, перебрасывать исключения можно, но нужно обернуть в свое например. Вот тут есть пример
https://detekt.dev/docs/rules/exceptions/#compliant-code-3

2022-05-06 11:22 UTC, alexdtat commented on src/main/kotlin/libraries/PerformedCommandStorage/PerformedCommandStorage.kt
> +    override val message: String
> Насколько я помню можно просто через равно прописать

Я не очень понял, как через равно, но можно через конструктор, вроде. И выглядит даже понятнее, пожалуй. Вроде такого: `class MoveInEmptyStorageException : IllegalArgumentException("Cannot move in the empty storage.")`

2022-05-11 12:18 UTC, SpirinEgor approved these changes
👍 
За совсем продолбанный дедлайн а-та-та, но что-то сделал и немного баллов заработал

2022-05-11 12:18 UTC, merged