Kotlin. Homework #3. Task #1
alexdtat/SPbU-Kotlin-course pull request #4
Opened 2022-04-30 12:37 UTC by alexdtat

AVLTree library has been added.

2022-05-02 13:20 UTC, alexdtat commented
Фильм ужасов про АВЛ-деревья.
![144229076-d7c826cf-7f90-40b9-a0b5-02a512ce7d92](https://user-images.githubusercontent.com/57017816/166240495-031d336e-dd6d-494d-8606-87ba44bd17c8.png)

2022-05-02 13:21 UTC, alexdtat commented
Долго мучался с явным итератором ( как в прошлом семестре), потом мне подсказали, что можно использовать вот такой многопоточный. Мне очень понравился трюк. :)

2022-05-06 10:40 UTC, GirZ0n requested changes
Красотища

2022-05-06 10:40 UTC, GirZ0n commented on src/main/kotlin/libraries/avlTree/AVLNode.kt
> +        val newRotationRoot: AVLNode<K, V> = rightChild ?: return this
А если убрать `AVLNode<K, V>`, то что-то поломается? :)

2022-05-06 10:40 UTC, GirZ0n commented on src/main/kotlin/libraries/avlTree/AVLNode.kt
> +        val newRotationRoot: AVLNode<K, V> = leftChild ?: return this
И тут тоже

2022-05-06 10:40 UTC, GirZ0n commented on src/main/kotlin/libraries/avlTree/AVLNode.kt
> +    fun printNode(indentSymbol: Char, indentStep: Int, indent: Int) {
Лучше не стоит выводит дерево сразу в stdout, пусть эта функция возвращает строку)

2022-05-06 10:40 UTC, GirZ0n commented on src/main/kotlin/libraries/avlTree/AVLTree.kt
> +            )
А зачем здесь такой перенос строк?) Вроде всё может поместится в одну строку.

2022-05-06 10:40 UTC, GirZ0n commented on src/main/kotlin/libraries/avlTree/AVLTree.kt
> +        }
Можно сразу `fun someFunction() = when {...}`

2022-05-06 10:40 UTC, GirZ0n commented on src/main/kotlin/libraries/avlTree/AVLTree.kt
> +    }
И тут тоже всё в одну строчку влезает :)

2022-05-06 10:40 UTC, GirZ0n commented on src/main/kotlin/libraries/avlTree/AVLTree.kt
> +        const val INDENT_STEP = 2
Эти константы используются только в `printNode`, так что наверно их стоит перенести в AVLNode)

2022-05-06 14:19 UTC, alexdtat commented on src/main/kotlin/libraries/avlTree/AVLTree.kt
> +            )
> А зачем здесь такой перенос строк?) Вроде всё может поместится в одну строку.

Кажется, идея предлагала, но мб это я просто через пкм случайно выбрал.

2022-05-08 10:05 UTC, GirZ0n requested changes
:fire:

2022-05-08 10:05 UTC, GirZ0n commented on src/main/kotlin/libraries/avlTree/AVLNode.kt
> +class AVLNode<K : Comparable<K>, V>(override val key: K, override var value: V) : MutableMap.MutableEntry<K, V> {
Ты при обращении к полям и функциям данного класса используешь `this`, этого можно не делать)

2022-05-08 10:05 UTC, GirZ0n commented on src/main/kotlin/libraries/avlTree/AVLTree.kt
> +        get() = root?.getNodeAsString(0)
Переопредели `toString` просто)

2022-05-08 10:05 UTC, GirZ0n commented on src/main/kotlin/libraries/avlTree/AVLTree.kt
> +    fun printTree() = println(root?.getNodeAsString(0))
А это лучше убрать. Пусть пользователь сам решает, что ему делать со строчкой)

2022-05-08 10:05 UTC, GirZ0n commented on src/main/kotlin/libraries/avlTree/AVLNode.kt
> +        }
Можно `let` использовать здесь

2022-05-08 19:56 UTC, alexdtat commented on src/main/kotlin/libraries/avlTree/AVLNode.kt
> +class AVLNode<K : Comparable<K>, V>(override val key: K, override var value: V) : MutableMap.MutableEntry<K, V> {
> Ты при обращении к полям и функциям данного класса используешь `this`, этого можно не делать)

А я-то думаю, что не так! У меня в других домашках даже из-за этого неполадки возникали. :)

2022-05-09 11:03 UTC, alexdtat commented on src/main/kotlin/libraries/avlTree/AVLTree.kt
> +        get() = root?.getNodeAsString(0)
> Переопредели `toString` просто)

Переопределить только для дерева достаточно будет?

2022-05-09 12:28 UTC, GirZ0n commented on src/main/kotlin/libraries/avlTree/AVLTree.kt
> +        get() = root?.getNodeAsString(0)
Ага

2022-05-09 19:41 UTC, GirZ0n approved these changes
:+1:

2022-05-09 19:41 UTC, GirZ0n commented on src/main/kotlin/libraries/avlTree/AVLNode.kt
> +        private const val INDENT_SYMBOL = '~'
А может тогда здесь использовать "~", чтобы в строчке 97 не писать `toString`?)

2022-05-09 19:41 UTC, GirZ0n commented on src/main/kotlin/libraries/avlTree/AVLNode.kt
> +        rightChild?.getStringNodeRecursive(indent + 1).let { if (it != null) nodeAsString += "r$it" }
Кажется, что можно просто `leftChild?.getStringNodeRecursive(indent + 1)?.let { nodeAsString += "l$it" }`.

2022-05-11 12:14 UTC, SpirinEgor approved these changes
👍

2022-05-11 12:14 UTC, merged