Kotlin. Homework #4. Task #1
alexdtat/SPbU-Kotlin-course pull request #8
Opened 2022-05-27 11:16 UTC by alexdtat

The solution has been added.

2022-05-27 11:21 UTC, alexdtat commented
Зависимость от количества потоков работает медленно, потому что там огромный список и довольно маленький шаг у самих потоков. По графику не заметна оптимизация от многопоточности, но, вероятнее всего, просто на создание потоков слишком много ресурсов уходит. Для корутин в следующей домашке есть дополнение.

2022-06-01 11:53 UTC, elena-lyulina requested changes

2022-06-01 11:53 UTC, elena-lyulina commented on src/main/kotlin/libraries/mergeSort/plot/Model.kt
> +const val FULL_PERCENTAGE = 100
глобальные константы вообще так себе идея, они видны ото всюду и если у тебя большое приложение, то получаются проблемы и страдает инкапсуляция
обычно все такие значения лучше хранить с свойствах класса или в том месте, где оно используется

2022-06-01 11:53 UTC, elena-lyulina commented on src/main/kotlin/homework/homework4and5/task_1.kt
> +    Window(
поправь, чтобы папки и файлы норм создавались, чтобы не было проблем при первом запуске

2022-06-01 11:53 UTC, elena-lyulina commented on src/main/kotlin/libraries/mergeSort/plot/Model.kt
> +const val FULL_PERCENTAGE = 100
ну и да, делать количество потоков по процентам от списка супер странно, обычно смотрят на количество ядер на машине, и так как их обычно 2-4-6-8-16-32-64, то лучше брать степени двойки и смотреть, как меняется от этого значения

2022-06-01 20:29 UTC, alexdtat commented
У меня вроде и до этого работало создание изображений, но сейчас дополнительно проверяется на наличие и, если надо, создаётся папка (как и все её предшественники) для них. Надеюсь, теперь всё корректно будет (у меня при удалении папки всё создалось и отработало нормально).

RadioButton удалил, т.к. корутины всё равно не работали и выдавали ошибку из-за TODO, а сама кнопка здесь была бесполезна.

Наверное, если в 5.1 всё ок будет, то лучше мержить её, а этот PR закрыть, потому что в 5.1 всё равно есть всё отсюда + архитектурные улучшения + корутины, зато не надо будет потом конфликты решать.

2022-06-02 11:31 UTC, elena-lyulina requested changes
Выглядит уже очень прилично и графики правдоподобные :) осталось чуть-чуть

2022-06-02 11:31 UTC, elena-lyulina commented on src/main/kotlin/libraries/mergeSort/plot/Model.kt
> +        val sizesToTimeMap = linkedMapOf<Int, Long>()
generatePlotTimeOnSize и generatePlotTimeOnParallelingResource получились супер похожи, подумай, мб можно вынести что-то в отдельные функции и избежать дублирования похожего кода

2022-06-02 18:45 UTC, merged