Kotlin. Homework #5. Task #1
alexdtat/SPbU-Kotlin-course pull request #9
Opened 2022-05-27 13:13 UTC by alexdtat

The solution has been added. Coroutines merge sort is available now. Model settings changes.

2022-05-27 13:28 UTC, alexdtat commented
Немного подкрутил настройки модели, чтобы при адекватном времени более-менее была видна разница между потоками и корутинами, но корутины не сортировали за константу.

2022-06-01 11:57 UTC, elena-lyulina requested changes

2022-06-01 11:57 UTC, elena-lyulina commented on src/main/kotlin/libraries/mergeSort/mergeSort.kt
> +        rightHalfSorting.join()
ты их по очереди запускаешь и в середине ждешь, пока первая корутина закончит работу, в чем смысл-то?

2022-06-01 11:57 UTC, elena-lyulina commented on src/main/kotlin/libraries/mergeSort/mergeSort.kt
> +private fun <T : Comparable<T>> MutableList<T>.multithreadedMergeSort(
у тебя есть две реализации сортировки -- время подумать над нормальной архитектурой и завести для сортировок один интерфейс, например, или абстрактный класс с общими методами типа merge
так, чтобы подменить одну реализацию на другую, можно будет просто передать нужный класс

2022-06-01 20:35 UTC, alexdtat commented
Если здесь всё в порядке, то лучше эту ветку замержить, а PR для 4.1 закрыть, чтобы не было конфликтов (всё равно эта ветка включает всю функциональность 4.1, корутины и некоторые улучшения).

2022-06-02 11:33 UTC, elena-lyulina approved these changes
Да, выглядит хорошо, поправь комменты к 4.1 и вмержь их сюда, а я солью потом этот пр

2022-06-02 18:45 UTC, merged